name       : winetricks
version    : 2020.12.06
release    : 21
source     :
    - https://github.com/Winetricks/winetricks/archive/20201206.tar.gz : 2eb5c09e30be942383e242694e654aa294ed2a396e68c68b5eaa17427bd8242b
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
