name       : winetricks
version    : 2021.02.06
release    : 24
source     :
    - https://github.com/Winetricks/winetricks/releases/download/20210206/20210206.tar.gz : 705421798b28696f577104ebdf03b068b9343ab096754150f47a6ec06fa8ae65
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
setup      : |
    %apply_patches
install    : |
    %make_install
