name       : winetricks
version    : '20180217'
release    : 11
source     :
    - https://github.com/Winetricks/winetricks/archive/20180217.tar.gz : 10e11dd150f1629af17f5549404d66b17968130cbdec6a4524b51d9291484a47
license    : LGPL-2.1
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
