name       : winetricks
version    : '20170101'
release    : 4
source     :
    - https://github.com/Winetricks/winetricks/archive/20170101.tar.gz : 3862ce2d94132484cb7fced13ccef6a7d1e94d75b5ee96b269d1bc45309f7b49
license    : LGPL-2.1
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - wine
    - cabextract
install    : |
    cd src
    install -D -m 755 winetricks %installroot%/usr/bin/winetricks
    install -D -m 644 winetricks.1 %installroot%/usr/man/man1/winetricks.1
    install -D -m 644 COPYING %installroot%/usr/share/doc/winetricks/COPYING
