name       : winetricks
version    : '20170614'
release    : 7
source     :
    - https://github.com/Winetricks/winetricks/archive/20170614.tar.gz : c31a51b006511b0ee47c662ef0ef98dd77c6ae410b083927c27674200974d173
license    : LGPL-2.1
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
