name       : winetricks
version    : 2019.06.15
release    : 17
source     :
    - https://github.com/Winetricks/winetricks/archive/20190615.tar.gz : 2a5ebbd95e0ed0041f903148af19ba28d5b7e29a62db4501771dfffb7368fc42
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
