name       : winetricks
version    : 2019.12.24
release    : 19
source     :
    - https://github.com/Winetricks/winetricks/archive/20191224.tar.gz : c1223bb90e76c468f15784a701696a184aaee802bc9c236797166dea33d0d0a2
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
