name       : winetricks
version    : '20170823'
release    : 8
source     :
    - https://github.com/Winetricks/winetricks/archive/20170823.tar.gz : 0e7e007b0dd39f773213a5540e7c44e4105d9435ef067c0efdcc6fda70c029de
license    : LGPL-2.1
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
