name       : winetricks
version    : '20171222'
release    : 10
source     :
    - https://github.com/Winetricks/winetricks/archive/20171222.tar.gz : 971e1979c87375979cef4d2ca3335b8993df2454932ffc4956cb8588b49bd04d
license    : LGPL-2.1
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
