name       : winetricks
version    : 2021.08.25
release    : 26
source     :
    - https://github.com/Winetricks/winetricks/archive/refs/tags/20210825.tar.gz : bac77918ef4d58c6465a1043fd996d09c3ee2c5a07f56ed089c4c65a71881277
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
setup      : |
    %patch -p1 < $pkgfiles/vcrun2019-update-sha256sum.patch
install    : |
    %make_install
