name       : winetricks
version    : 20180513
release    : 12
source     :
    - https://github.com/Winetricks/winetricks/archive/20180513.tar.gz : 626aff64e3d93698704b0b668225d5504fd8ef556e3834f569058deaeafada8e
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
