name       : winetricks
version    : 2018.05.15
release    : 14
source     :
    - https://github.com/Winetricks/winetricks/archive/20180815.tar.gz : 6dc22357ea1f857b7283250f7c6a68b9dee97e672bbea9a9c45c573d73634200
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
