name       : winetricks
version    : 2022.04.11
release    : 27
source     :
    - https://github.com/Winetricks/winetricks/archive/refs/tags/20220411.tar.gz : c16e09ee4e5fda48a49ae9515a9c6d175713792be1b85ea92624d93e37effbd0
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
