name       : winetricks
version    : 20151110
release    : 1
source     :
    - https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks : f7c324460420c2420c02533b90d3f9b2d8bdf71e16c1aa3aa80767c412c4851a
license    : GPL-2.0+
summary    : Winetricks pacakge manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - wine
extract    : no
install    : |
    pushd $sources
    install -D -m 755 winetricks %installroot%/usr/bin/winetricks
