name       : winetricks
version    : 2019.03.10
release    : 16
source     :
    - https://github.com/Winetricks/winetricks/archive/20190310.tar.gz : dc86847c1c9bffd7622bd9095178b913210177f1a9c8f302e9d4e72ba39f9ff6
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
