name       : winetricks
version    : 20180603
release    : 13
source     :
    - https://github.com/Winetricks/winetricks/archive/20180603.tar.gz : 66d8b48e001136d6d68b4c467c740753c56becceab9138632b479cb6c559074f
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
