name       : winetricks
version    : 2020.04.12
release    : 20
source     :
    - https://github.com/Winetricks/winetricks/archive/20200412.tar.gz : 4b0aa4f11dbc30d10a8edd2bb83fcc34f9b143ab58ccce7b99cd54ebff7ec260
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
