name       : winetricks
version    : 2018.12.03
release    : 15
source     :
    - https://github.com/Winetricks/winetricks/archive/20181203.tar.gz : 7144b86b499a4db733efd1f8c360555c64a1ec60af6b1049be06ee88decfcb91
license    : LGPL-2.1-or-later
component  : virt
summary    : Winetricks package manager
description: |
    Winetricks is a package manager for win32 dlls and applications on posix.
rundeps    :
    - cabextract
    - wine-32bit
install    : |
    %make_install
